spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/analytics_db
spring.datasource.username=postgres
spring.datasource.password=Kitty@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
openrouter.api.key = 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

# ==========================
# GROQ CONFIGURATION
# ==========================

groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.api.key=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
groq.model=llama-3.3-70b-versatile